
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImV4cCI6MTYyNDQ0Nzg4Nn0.h93o-lWpjk9M2LtTF0HJi9doBZr_JWJRNEwn7pLWN-g
# Get all Instruments 

@token2 = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDQ0ODA2MH0.3nTlq82Eo2u2ljw3AaIsaaL55FyvRQPRQ3WdeASQcys
GET http://localhost:8000/api/instruments/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Get single Instruments 
GET http://localhost:8000/api/instruments/1/

###
# Register a User

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "password":"Drew123456789",
  "passwordConfirmation": "Drew123456789",
  "username": "Drew",
  "email": "Drew@email.com",
  "firstName": "Drew",
  "lastName":"Lamph",
  "bio": "Hello World",
  "userType":"Student",
  "instrumentType": "Piano",
  "locationTypeChoices": "London"
}

###

# Login a User
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "Drew@email.com",
  "password": "Drew123456789"
}

###
# Send a message
POST http://localhost:8000/api/conversations/1/conversations/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  

  "text": "hello how are you "
} 


###
# View User Profile
GET http://localhost:8000/api/auth/profile/
Content-Type: application/json
Authorization: Bearer {{token}}

###
# Register second User

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "password":"Dimi123456789",
  "passwordConfirmation": "Dimi123456789",
  "username": "Dimi",
  "email": "dimi@email.com",
  "firstName": "Dimi",
  "lastName":"Tsonev",
  "bio": "Hello Drew",
  "userType":"Student",
  "instrumentType": "Piano",
  "locationTypeChoices": "London"
}
###
# Login second User

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "dimi@email.com",
  "password": "Dimi123456789"
}

###
# Showing all conversations
GET http://localhost:8000/api/conversations/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a review
POST http://localhost:8000/api/reviews/2/reviews/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user": 2,
  "content": "First Review",
  "created_at": "",
  "rating": 1
}