# Generated by Django 3.2.4 on 2021-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=700)),
                ('image', models.CharField(max_length=250)),
                ('media', models.CharField(max_length=250)),
            ],
        ),
    ]
