# Generated by Django 3.2.4 on 2021-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_family',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
