# Generated by Django 3.2.4 on 2021-06-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_instrument_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_family',
        ),
    ]
