# Generated by Django 3.2.4 on 2021-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_instrument_instrument_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
